require "keymaps"
require "lazy-config"
require "options"


require "alpha-config"
require "nvim-tree-config"
require "hop-config"
require "comment-config"
require "lualine-config"
require "bufferline-config"
require "telescope"
require "treesitter-config"
require "lsp-config"
require "whichkey"
